// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airpay.proto

package airpay;

public final class Airpay {
  private Airpay() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PacketHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:airpay.PacketHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 id = 1;</code>
     */
    int getId();

    /**
     * <code>uint32 result = 2;</code>
     */
    int getResult();

    /**
     * <code>string message = 3;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 3;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code airpay.PacketHeader}
   */
  public  static final class PacketHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:airpay.PacketHeader)
      PacketHeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PacketHeader.newBuilder() to construct.
    private PacketHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PacketHeader() {
      id_ = 0;
      result_ = 0;
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PacketHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readUInt32();
              break;
            }
            case 16: {

              result_ = input.readUInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return airpay.Airpay.internal_static_airpay_PacketHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return airpay.Airpay.internal_static_airpay_PacketHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              airpay.Airpay.PacketHeader.class, airpay.Airpay.PacketHeader.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int RESULT_FIELD_NUMBER = 2;
    private int result_;
    /**
     * <code>uint32 result = 2;</code>
     */
    public int getResult() {
      return result_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 3;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeUInt32(1, id_);
      }
      if (result_ != 0) {
        output.writeUInt32(2, result_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (result_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, result_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof airpay.Airpay.PacketHeader)) {
        return super.equals(obj);
      }
      airpay.Airpay.PacketHeader other = (airpay.Airpay.PacketHeader) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getResult()
          == other.getResult());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static airpay.Airpay.PacketHeader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static airpay.Airpay.PacketHeader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static airpay.Airpay.PacketHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static airpay.Airpay.PacketHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static airpay.Airpay.PacketHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static airpay.Airpay.PacketHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static airpay.Airpay.PacketHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static airpay.Airpay.PacketHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static airpay.Airpay.PacketHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static airpay.Airpay.PacketHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static airpay.Airpay.PacketHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static airpay.Airpay.PacketHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(airpay.Airpay.PacketHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code airpay.PacketHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:airpay.PacketHeader)
        airpay.Airpay.PacketHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return airpay.Airpay.internal_static_airpay_PacketHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return airpay.Airpay.internal_static_airpay_PacketHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                airpay.Airpay.PacketHeader.class, airpay.Airpay.PacketHeader.Builder.class);
      }

      // Construct using airpay.Airpay.PacketHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        result_ = 0;

        message_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return airpay.Airpay.internal_static_airpay_PacketHeader_descriptor;
      }

      public airpay.Airpay.PacketHeader getDefaultInstanceForType() {
        return airpay.Airpay.PacketHeader.getDefaultInstance();
      }

      public airpay.Airpay.PacketHeader build() {
        airpay.Airpay.PacketHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public airpay.Airpay.PacketHeader buildPartial() {
        airpay.Airpay.PacketHeader result = new airpay.Airpay.PacketHeader(this);
        result.id_ = id_;
        result.result_ = result_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof airpay.Airpay.PacketHeader) {
          return mergeFrom((airpay.Airpay.PacketHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(airpay.Airpay.PacketHeader other) {
        if (other == airpay.Airpay.PacketHeader.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getResult() != 0) {
          setResult(other.getResult());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        airpay.Airpay.PacketHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (airpay.Airpay.PacketHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int result_ ;
      /**
       * <code>uint32 result = 2;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>uint32 result = 2;</code>
       */
      public Builder setResult(int value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 result = 2;</code>
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 3;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 3;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 3;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 3;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:airpay.PacketHeader)
    }

    // @@protoc_insertion_point(class_scope:airpay.PacketHeader)
    private static final airpay.Airpay.PacketHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new airpay.Airpay.PacketHeader();
    }

    public static airpay.Airpay.PacketHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PacketHeader>
        PARSER = new com.google.protobuf.AbstractParser<PacketHeader>() {
      public PacketHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PacketHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PacketHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PacketHeader> getParserForType() {
      return PARSER;
    }

    public airpay.Airpay.PacketHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:airpay.LoginRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.airpay.PacketHeader header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>.airpay.PacketHeader header = 1;</code>
     */
    airpay.Airpay.PacketHeader getHeader();
    /**
     * <code>.airpay.PacketHeader header = 1;</code>
     */
    airpay.Airpay.PacketHeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>uint64 uid = 2;</code>
     */
    long getUid();

    /**
     * <code>string device_key = 3;</code>
     */
    java.lang.String getDeviceKey();
    /**
     * <code>string device_key = 3;</code>
     */
    com.google.protobuf.ByteString
        getDeviceKeyBytes();

    /**
     * <code>uint32 device_type = 4;</code>
     */
    int getDeviceType();

    /**
     * <code>string login_password = 5;</code>
     */
    java.lang.String getLoginPassword();
    /**
     * <code>string login_password = 5;</code>
     */
    com.google.protobuf.ByteString
        getLoginPasswordBytes();

    /**
     * <code>string notify_key = 6;</code>
     */
    java.lang.String getNotifyKey();
    /**
     * <code>string notify_key = 6;</code>
     */
    com.google.protobuf.ByteString
        getNotifyKeyBytes();

    /**
     * <code>uint32 version = 7;</code>
     */
    int getVersion();

    /**
     * <code>uint32 notify_type = 8;</code>
     */
    int getNotifyType();
  }
  /**
   * Protobuf type {@code airpay.LoginRequest}
   */
  public  static final class LoginRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:airpay.LoginRequest)
      LoginRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LoginRequest.newBuilder() to construct.
    private LoginRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginRequest() {
      uid_ = 0L;
      deviceKey_ = "";
      deviceType_ = 0;
      loginPassword_ = "";
      notifyKey_ = "";
      version_ = 0;
      notifyType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LoginRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              airpay.Airpay.PacketHeader.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(airpay.Airpay.PacketHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              uid_ = input.readUInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceKey_ = s;
              break;
            }
            case 32: {

              deviceType_ = input.readUInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              loginPassword_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              notifyKey_ = s;
              break;
            }
            case 56: {

              version_ = input.readUInt32();
              break;
            }
            case 64: {

              notifyType_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return airpay.Airpay.internal_static_airpay_LoginRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return airpay.Airpay.internal_static_airpay_LoginRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              airpay.Airpay.LoginRequest.class, airpay.Airpay.LoginRequest.Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private airpay.Airpay.PacketHeader header_;
    /**
     * <code>.airpay.PacketHeader header = 1;</code>
     */
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.airpay.PacketHeader header = 1;</code>
     */
    public airpay.Airpay.PacketHeader getHeader() {
      return header_ == null ? airpay.Airpay.PacketHeader.getDefaultInstance() : header_;
    }
    /**
     * <code>.airpay.PacketHeader header = 1;</code>
     */
    public airpay.Airpay.PacketHeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int UID_FIELD_NUMBER = 2;
    private long uid_;
    /**
     * <code>uint64 uid = 2;</code>
     */
    public long getUid() {
      return uid_;
    }

    public static final int DEVICE_KEY_FIELD_NUMBER = 3;
    private volatile java.lang.Object deviceKey_;
    /**
     * <code>string device_key = 3;</code>
     */
    public java.lang.String getDeviceKey() {
      java.lang.Object ref = deviceKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceKey_ = s;
        return s;
      }
    }
    /**
     * <code>string device_key = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceKeyBytes() {
      java.lang.Object ref = deviceKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICE_TYPE_FIELD_NUMBER = 4;
    private int deviceType_;
    /**
     * <code>uint32 device_type = 4;</code>
     */
    public int getDeviceType() {
      return deviceType_;
    }

    public static final int LOGIN_PASSWORD_FIELD_NUMBER = 5;
    private volatile java.lang.Object loginPassword_;
    /**
     * <code>string login_password = 5;</code>
     */
    public java.lang.String getLoginPassword() {
      java.lang.Object ref = loginPassword_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        loginPassword_ = s;
        return s;
      }
    }
    /**
     * <code>string login_password = 5;</code>
     */
    public com.google.protobuf.ByteString
        getLoginPasswordBytes() {
      java.lang.Object ref = loginPassword_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loginPassword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NOTIFY_KEY_FIELD_NUMBER = 6;
    private volatile java.lang.Object notifyKey_;
    /**
     * <code>string notify_key = 6;</code>
     */
    public java.lang.String getNotifyKey() {
      java.lang.Object ref = notifyKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        notifyKey_ = s;
        return s;
      }
    }
    /**
     * <code>string notify_key = 6;</code>
     */
    public com.google.protobuf.ByteString
        getNotifyKeyBytes() {
      java.lang.Object ref = notifyKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        notifyKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 7;
    private int version_;
    /**
     * <code>uint32 version = 7;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int NOTIFY_TYPE_FIELD_NUMBER = 8;
    private int notifyType_;
    /**
     * <code>uint32 notify_type = 8;</code>
     */
    public int getNotifyType() {
      return notifyType_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (uid_ != 0L) {
        output.writeUInt64(2, uid_);
      }
      if (!getDeviceKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, deviceKey_);
      }
      if (deviceType_ != 0) {
        output.writeUInt32(4, deviceType_);
      }
      if (!getLoginPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, loginPassword_);
      }
      if (!getNotifyKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, notifyKey_);
      }
      if (version_ != 0) {
        output.writeUInt32(7, version_);
      }
      if (notifyType_ != 0) {
        output.writeUInt32(8, notifyType_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (uid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, uid_);
      }
      if (!getDeviceKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, deviceKey_);
      }
      if (deviceType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, deviceType_);
      }
      if (!getLoginPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, loginPassword_);
      }
      if (!getNotifyKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, notifyKey_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, version_);
      }
      if (notifyType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, notifyType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof airpay.Airpay.LoginRequest)) {
        return super.equals(obj);
      }
      airpay.Airpay.LoginRequest other = (airpay.Airpay.LoginRequest) obj;

      boolean result = true;
      result = result && (hasHeader() == other.hasHeader());
      if (hasHeader()) {
        result = result && getHeader()
            .equals(other.getHeader());
      }
      result = result && (getUid()
          == other.getUid());
      result = result && getDeviceKey()
          .equals(other.getDeviceKey());
      result = result && (getDeviceType()
          == other.getDeviceType());
      result = result && getLoginPassword()
          .equals(other.getLoginPassword());
      result = result && getNotifyKey()
          .equals(other.getNotifyKey());
      result = result && (getVersion()
          == other.getVersion());
      result = result && (getNotifyType()
          == other.getNotifyType());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUid());
      hash = (37 * hash) + DEVICE_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceKey().hashCode();
      hash = (37 * hash) + DEVICE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceType();
      hash = (37 * hash) + LOGIN_PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getLoginPassword().hashCode();
      hash = (37 * hash) + NOTIFY_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getNotifyKey().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + NOTIFY_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getNotifyType();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static airpay.Airpay.LoginRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static airpay.Airpay.LoginRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static airpay.Airpay.LoginRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static airpay.Airpay.LoginRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static airpay.Airpay.LoginRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static airpay.Airpay.LoginRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static airpay.Airpay.LoginRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static airpay.Airpay.LoginRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static airpay.Airpay.LoginRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static airpay.Airpay.LoginRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static airpay.Airpay.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static airpay.Airpay.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(airpay.Airpay.LoginRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code airpay.LoginRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:airpay.LoginRequest)
        airpay.Airpay.LoginRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return airpay.Airpay.internal_static_airpay_LoginRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return airpay.Airpay.internal_static_airpay_LoginRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                airpay.Airpay.LoginRequest.class, airpay.Airpay.LoginRequest.Builder.class);
      }

      // Construct using airpay.Airpay.LoginRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        uid_ = 0L;

        deviceKey_ = "";

        deviceType_ = 0;

        loginPassword_ = "";

        notifyKey_ = "";

        version_ = 0;

        notifyType_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return airpay.Airpay.internal_static_airpay_LoginRequest_descriptor;
      }

      public airpay.Airpay.LoginRequest getDefaultInstanceForType() {
        return airpay.Airpay.LoginRequest.getDefaultInstance();
      }

      public airpay.Airpay.LoginRequest build() {
        airpay.Airpay.LoginRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public airpay.Airpay.LoginRequest buildPartial() {
        airpay.Airpay.LoginRequest result = new airpay.Airpay.LoginRequest(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        result.uid_ = uid_;
        result.deviceKey_ = deviceKey_;
        result.deviceType_ = deviceType_;
        result.loginPassword_ = loginPassword_;
        result.notifyKey_ = notifyKey_;
        result.version_ = version_;
        result.notifyType_ = notifyType_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof airpay.Airpay.LoginRequest) {
          return mergeFrom((airpay.Airpay.LoginRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(airpay.Airpay.LoginRequest other) {
        if (other == airpay.Airpay.LoginRequest.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.getUid() != 0L) {
          setUid(other.getUid());
        }
        if (!other.getDeviceKey().isEmpty()) {
          deviceKey_ = other.deviceKey_;
          onChanged();
        }
        if (other.getDeviceType() != 0) {
          setDeviceType(other.getDeviceType());
        }
        if (!other.getLoginPassword().isEmpty()) {
          loginPassword_ = other.loginPassword_;
          onChanged();
        }
        if (!other.getNotifyKey().isEmpty()) {
          notifyKey_ = other.notifyKey_;
          onChanged();
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.getNotifyType() != 0) {
          setNotifyType(other.getNotifyType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        airpay.Airpay.LoginRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (airpay.Airpay.LoginRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private airpay.Airpay.PacketHeader header_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          airpay.Airpay.PacketHeader, airpay.Airpay.PacketHeader.Builder, airpay.Airpay.PacketHeaderOrBuilder> headerBuilder_;
      /**
       * <code>.airpay.PacketHeader header = 1;</code>
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.airpay.PacketHeader header = 1;</code>
       */
      public airpay.Airpay.PacketHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? airpay.Airpay.PacketHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.airpay.PacketHeader header = 1;</code>
       */
      public Builder setHeader(airpay.Airpay.PacketHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.airpay.PacketHeader header = 1;</code>
       */
      public Builder setHeader(
          airpay.Airpay.PacketHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.airpay.PacketHeader header = 1;</code>
       */
      public Builder mergeHeader(airpay.Airpay.PacketHeader value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              airpay.Airpay.PacketHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.airpay.PacketHeader header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.airpay.PacketHeader header = 1;</code>
       */
      public airpay.Airpay.PacketHeader.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.airpay.PacketHeader header = 1;</code>
       */
      public airpay.Airpay.PacketHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              airpay.Airpay.PacketHeader.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.airpay.PacketHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          airpay.Airpay.PacketHeader, airpay.Airpay.PacketHeader.Builder, airpay.Airpay.PacketHeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              airpay.Airpay.PacketHeader, airpay.Airpay.PacketHeader.Builder, airpay.Airpay.PacketHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private long uid_ ;
      /**
       * <code>uint64 uid = 2;</code>
       */
      public long getUid() {
        return uid_;
      }
      /**
       * <code>uint64 uid = 2;</code>
       */
      public Builder setUid(long value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 uid = 2;</code>
       */
      public Builder clearUid() {
        
        uid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object deviceKey_ = "";
      /**
       * <code>string device_key = 3;</code>
       */
      public java.lang.String getDeviceKey() {
        java.lang.Object ref = deviceKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string device_key = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceKeyBytes() {
        java.lang.Object ref = deviceKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string device_key = 3;</code>
       */
      public Builder setDeviceKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string device_key = 3;</code>
       */
      public Builder clearDeviceKey() {
        
        deviceKey_ = getDefaultInstance().getDeviceKey();
        onChanged();
        return this;
      }
      /**
       * <code>string device_key = 3;</code>
       */
      public Builder setDeviceKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceKey_ = value;
        onChanged();
        return this;
      }

      private int deviceType_ ;
      /**
       * <code>uint32 device_type = 4;</code>
       */
      public int getDeviceType() {
        return deviceType_;
      }
      /**
       * <code>uint32 device_type = 4;</code>
       */
      public Builder setDeviceType(int value) {
        
        deviceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 device_type = 4;</code>
       */
      public Builder clearDeviceType() {
        
        deviceType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object loginPassword_ = "";
      /**
       * <code>string login_password = 5;</code>
       */
      public java.lang.String getLoginPassword() {
        java.lang.Object ref = loginPassword_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          loginPassword_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string login_password = 5;</code>
       */
      public com.google.protobuf.ByteString
          getLoginPasswordBytes() {
        java.lang.Object ref = loginPassword_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          loginPassword_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string login_password = 5;</code>
       */
      public Builder setLoginPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        loginPassword_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string login_password = 5;</code>
       */
      public Builder clearLoginPassword() {
        
        loginPassword_ = getDefaultInstance().getLoginPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string login_password = 5;</code>
       */
      public Builder setLoginPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        loginPassword_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object notifyKey_ = "";
      /**
       * <code>string notify_key = 6;</code>
       */
      public java.lang.String getNotifyKey() {
        java.lang.Object ref = notifyKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          notifyKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string notify_key = 6;</code>
       */
      public com.google.protobuf.ByteString
          getNotifyKeyBytes() {
        java.lang.Object ref = notifyKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          notifyKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string notify_key = 6;</code>
       */
      public Builder setNotifyKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        notifyKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string notify_key = 6;</code>
       */
      public Builder clearNotifyKey() {
        
        notifyKey_ = getDefaultInstance().getNotifyKey();
        onChanged();
        return this;
      }
      /**
       * <code>string notify_key = 6;</code>
       */
      public Builder setNotifyKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        notifyKey_ = value;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>uint32 version = 7;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>uint32 version = 7;</code>
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 version = 7;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private int notifyType_ ;
      /**
       * <code>uint32 notify_type = 8;</code>
       */
      public int getNotifyType() {
        return notifyType_;
      }
      /**
       * <code>uint32 notify_type = 8;</code>
       */
      public Builder setNotifyType(int value) {
        
        notifyType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 notify_type = 8;</code>
       */
      public Builder clearNotifyType() {
        
        notifyType_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:airpay.LoginRequest)
    }

    // @@protoc_insertion_point(class_scope:airpay.LoginRequest)
    private static final airpay.Airpay.LoginRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new airpay.Airpay.LoginRequest();
    }

    public static airpay.Airpay.LoginRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginRequest>
        PARSER = new com.google.protobuf.AbstractParser<LoginRequest>() {
      public LoginRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginRequest> getParserForType() {
      return PARSER;
    }

    public airpay.Airpay.LoginRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:airpay.LoginReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>string awesome_field = 1;</code>
     */
    java.lang.String getAwesomeField();
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>string awesome_field = 1;</code>
     */
    com.google.protobuf.ByteString
        getAwesomeFieldBytes();
  }
  /**
   * Protobuf type {@code airpay.LoginReply}
   */
  public  static final class LoginReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:airpay.LoginReply)
      LoginReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LoginReply.newBuilder() to construct.
    private LoginReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginReply() {
      awesomeField_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LoginReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              awesomeField_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return airpay.Airpay.internal_static_airpay_LoginReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return airpay.Airpay.internal_static_airpay_LoginReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              airpay.Airpay.LoginReply.class, airpay.Airpay.LoginReply.Builder.class);
    }

    public static final int AWESOME_FIELD_FIELD_NUMBER = 1;
    private volatile java.lang.Object awesomeField_;
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>string awesome_field = 1;</code>
     */
    public java.lang.String getAwesomeField() {
      java.lang.Object ref = awesomeField_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        awesomeField_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * becomes awesomeField
     * </pre>
     *
     * <code>string awesome_field = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAwesomeFieldBytes() {
      java.lang.Object ref = awesomeField_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        awesomeField_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAwesomeFieldBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, awesomeField_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAwesomeFieldBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, awesomeField_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof airpay.Airpay.LoginReply)) {
        return super.equals(obj);
      }
      airpay.Airpay.LoginReply other = (airpay.Airpay.LoginReply) obj;

      boolean result = true;
      result = result && getAwesomeField()
          .equals(other.getAwesomeField());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AWESOME_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + getAwesomeField().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static airpay.Airpay.LoginReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static airpay.Airpay.LoginReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static airpay.Airpay.LoginReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static airpay.Airpay.LoginReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static airpay.Airpay.LoginReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static airpay.Airpay.LoginReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static airpay.Airpay.LoginReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static airpay.Airpay.LoginReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static airpay.Airpay.LoginReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static airpay.Airpay.LoginReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static airpay.Airpay.LoginReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static airpay.Airpay.LoginReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(airpay.Airpay.LoginReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code airpay.LoginReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:airpay.LoginReply)
        airpay.Airpay.LoginReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return airpay.Airpay.internal_static_airpay_LoginReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return airpay.Airpay.internal_static_airpay_LoginReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                airpay.Airpay.LoginReply.class, airpay.Airpay.LoginReply.Builder.class);
      }

      // Construct using airpay.Airpay.LoginReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        awesomeField_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return airpay.Airpay.internal_static_airpay_LoginReply_descriptor;
      }

      public airpay.Airpay.LoginReply getDefaultInstanceForType() {
        return airpay.Airpay.LoginReply.getDefaultInstance();
      }

      public airpay.Airpay.LoginReply build() {
        airpay.Airpay.LoginReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public airpay.Airpay.LoginReply buildPartial() {
        airpay.Airpay.LoginReply result = new airpay.Airpay.LoginReply(this);
        result.awesomeField_ = awesomeField_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof airpay.Airpay.LoginReply) {
          return mergeFrom((airpay.Airpay.LoginReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(airpay.Airpay.LoginReply other) {
        if (other == airpay.Airpay.LoginReply.getDefaultInstance()) return this;
        if (!other.getAwesomeField().isEmpty()) {
          awesomeField_ = other.awesomeField_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        airpay.Airpay.LoginReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (airpay.Airpay.LoginReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object awesomeField_ = "";
      /**
       * <pre>
       * becomes awesomeField
       * </pre>
       *
       * <code>string awesome_field = 1;</code>
       */
      public java.lang.String getAwesomeField() {
        java.lang.Object ref = awesomeField_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          awesomeField_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * becomes awesomeField
       * </pre>
       *
       * <code>string awesome_field = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAwesomeFieldBytes() {
        java.lang.Object ref = awesomeField_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          awesomeField_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * becomes awesomeField
       * </pre>
       *
       * <code>string awesome_field = 1;</code>
       */
      public Builder setAwesomeField(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        awesomeField_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * becomes awesomeField
       * </pre>
       *
       * <code>string awesome_field = 1;</code>
       */
      public Builder clearAwesomeField() {
        
        awesomeField_ = getDefaultInstance().getAwesomeField();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * becomes awesomeField
       * </pre>
       *
       * <code>string awesome_field = 1;</code>
       */
      public Builder setAwesomeFieldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        awesomeField_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:airpay.LoginReply)
    }

    // @@protoc_insertion_point(class_scope:airpay.LoginReply)
    private static final airpay.Airpay.LoginReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new airpay.Airpay.LoginReply();
    }

    public static airpay.Airpay.LoginReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginReply>
        PARSER = new com.google.protobuf.AbstractParser<LoginReply>() {
      public LoginReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginReply> getParserForType() {
      return PARSER;
    }

    public airpay.Airpay.LoginReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airpay_PacketHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airpay_PacketHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airpay_LoginRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airpay_LoginRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airpay_LoginReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airpay_LoginReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014airpay.proto\022\006airpay\";\n\014PacketHeader\022\n" +
      "\n\002id\030\001 \001(\r\022\016\n\006result\030\002 \001(\r\022\017\n\007message\030\003 " +
      "\001(\t\"\274\001\n\014LoginRequest\022$\n\006header\030\001 \001(\0132\024.a" +
      "irpay.PacketHeader\022\013\n\003uid\030\002 \001(\004\022\022\n\ndevic" +
      "e_key\030\003 \001(\t\022\023\n\013device_type\030\004 \001(\r\022\026\n\016logi" +
      "n_password\030\005 \001(\t\022\022\n\nnotify_key\030\006 \001(\t\022\017\n\007" +
      "version\030\007 \001(\r\022\023\n\013notify_type\030\010 \001(\r\"#\n\nLo" +
      "ginReply\022\025\n\rawesome_field\030\001 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_airpay_PacketHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_airpay_PacketHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airpay_PacketHeader_descriptor,
        new java.lang.String[] { "Id", "Result", "Message", });
    internal_static_airpay_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_airpay_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airpay_LoginRequest_descriptor,
        new java.lang.String[] { "Header", "Uid", "DeviceKey", "DeviceType", "LoginPassword", "NotifyKey", "Version", "NotifyType", });
    internal_static_airpay_LoginReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_airpay_LoginReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airpay_LoginReply_descriptor,
        new java.lang.String[] { "AwesomeField", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
